version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - EXTERNAL_API_URL=https://dummyjson.com/products/search?q=phone

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
